// Full Name: Adrian Iorga
// Student #: 124180191
// Seneca Email: aiorga - at - myseneca.ca
// Class: WEB322 NAA
// Assignment - Meal Kit Website
// ********************************

module.exports = [
    {
        id: 1,
        image: 'pexels-lisa-fotios-1351238-min.jpg',
        title: 'Spinach Veggie Spread',
        included: 'all grain toast, spinach, greens, herb spices',
        description: '',
        category: 'breakfast',
        price: 11.84,
        cookingTime: 15,
        servings: 2,
        calories: 284,
        type: "vegan",
        top: true
    },
    {
        id: 2,
        image: 'pexels-trang-doan-793785-min.jpg',
        title: 'Soft Boiled Egg Toast',
        included: 'whole wheat toast, eggs, berries, avocado',
        description: '',
        category: 'breakfast',
        price: 9.34,
        cookingTime: 20,
        servings: 2,
        calories: 493,
        type: "vegan",
        top: true
    },
    {
        id: 3,
        image: 'pexels-kasumi-loffler-3535380-min.jpg',
        title: 'Avocado Lime Sandwich',
        included: 'all grain bread, avocado, lime, kale',
        description: '',
        category: 'breakfast',
        price: 9.34,
        cookingTime: 10,
        servings: 2,
        calories: 415,
        type: "vegan",
        top: false
    },
    {
        id: 4,
        image: 'pexels-bulbfish-1143754-min.jpg',
        title: 'Crunchy Tomato Wraps',
        included: 'avocado, tomato, spices, tortilla wrap',
        description: '',
        category: 'breakfast',
        price: 8.19,
        cookingTime: 12,
        servings: 2,
        calories: 348,
        type: "vegan",
        top: false
    },
    {
        id: 5,
        image: 'pexels-engin-akyurt-2347311-min.jpg',
        title: 'Veggie Fried Noodle',
        included: 'rice noodle, red pepper, brocolli, siracha',
        description: '',
        category: 'lunch',
        price: 12.34,
        cookingTime: 25,
        servings: 2,
        calories: 688,
        type: "vegan",
        top: true
    },
    {
        id: 8,
        image: 'pexels-pixabay-209540-min.jpg',
        title: 'Steamed Pumpkin Stew',
        included: 'mashed pumpkin, rosemary, beef',
        description: '',
        category: 'lunch',
        price: 14.31,
        cookingTime: 20,
        servings: 2,
        calories: 645,
        type: "vegan",
        top: true
    },
    {
        id: 7,
        image: 'pexels-engin-akyurt-2697229-min.jpg',
        title: 'Creamy Carbonara Pasta',
        included: 'noodles, mushroom, bell pepper, chicken',
        description: '',
        category: 'lunch',
        price: 13.56,
        cookingTime: 30,
        servings: 2,
        calories: 784,
        type: "meat",
        top: false
    },
    {
        id: 6,
        image: 'pexels-foodie-factor-539451-min.jpg',
        title: 'Squash Mash Soup',
        included: 'squash, greens, spices, fresh basil',
        description: '',
        category: 'lunch',
        price: 11.21,
        cookingTime: 30,
        servings: 2,
        calories: 553,
        type: "vegan",
        top: false
    },
    {
        id: 9,
        image: 'pexels-malidate-van-769289-min.jpg',
        title: '100% Canadian Steak',
        included: 'beef, carrots, brocolli, spicy mustard',
        description: '',
        category: 'dinner',
        price: 24.15,
        cookingTime: 35,
        servings: 2,
        calories: 486,
        type: "meat",
        top: true
    },
    {
        id: 10,
        image: 'pexels-malidate-van-842142-min.jpg',
        title: 'Butter Crusted Salmon',
        included: 'atlantic salmon, zuchinni, peppers',
        description: '',
        category: 'dinner',
        price: 22.31,
        cookingTime: 30,
        servings: 1,
        calories: 745,
        type: "fish",
        top: true
    },
    {
        id: 11,
        image: 'pexels-pascal-claivaz-410648-min.jpg',
        title: 'Whole Rack Lamb Ribs',
        included: 'lamb ribs, spices, greens',
        description: '',
        category: 'dinner',
        price: 34.91,
        cookingTime: 40,
        servings: 2,
        calories: 845,
        type: "meat",
        top: false
    },
    {
        id: 12,
        image: 'pexels-sebastian-coman-photography-3510155-min.jpg',
        title: 'Salted Brussel Sprouts',
        included: 'brussel sprouts, sea salt, olive oil',
        description: '',
        category: 'dinner',
        price: 9.31,
        cookingTime: 25,
        servings: 1,
        calories: 248,
        type: "vegan",
        top: false
    }
];